/**
 * Tests for Argon2Hash() — the preferred Argon2 hashing function.
 *
 * History:
 *   - GenerateArgon2Hash() was the original name (from extension-argon2), now deprecated.
 *     It uses weak defaults (argon2i, 8 KB memory, 1 iteration) for backwards compat.
 *   - Argon2Hash() uses OWASP-recommended defaults (argon2id, 19456 KB memory, 2 iterations).
 *   - Existing tests for the deprecated GenerateArgon2Hash() remain in tests/Argon2.cfc.
 */
component extends="org.lucee.cfml.test.LuceeTestCase" labels="crypto" {

	function run( testResults, testBox ) {

		describe( "Argon2Hash defaults (OWASP)", function() {

			it( "defaults to argon2id variant", function() {
				var hash = Argon2Hash( "password" );

				expect( hash ).toBeString();
				expect( hash ).toInclude( "$argon2id$" );
			});

			it( "defaults to 19456 KB memory and 2 iterations", function() {
				var hash = Argon2Hash( "password" );

				// PHC format: $argon2id$v=19$m=19456,t=2,p=1$salt$hash
				expect( hash ).toMatch( "m=19456," );
				expect( hash ).toMatch( ",t=2," );
			});

			it( "generates different hashes for same input (random salt)", function() {
				var hash1 = Argon2Hash( "password" );
				var hash2 = Argon2Hash( "password" );

				expect( hash1 ).notToBe( hash2 );
			});

		});

		describe( "Argon2Hash with custom parameters", function() {

			it( "supports argon2i variant", function() {
				// Use low params for speed in tests
				var hash = Argon2Hash( "password", "argon2i", 1, 8, 1 );
				expect( hash ).toInclude( "$argon2i$" );
			});

			it( "supports argon2d variant", function() {
				var hash = Argon2Hash( "password", "argon2d", 1, 8, 1 );
				expect( hash ).toInclude( "$argon2d$" );
			});

			it( "supports argon2id variant explicitly", function() {
				var hash = Argon2Hash( "password", "argon2id", 1, 8, 1 );
				expect( hash ).toInclude( "$argon2id$" );
			});

			it( "respects custom memory and iteration params", function() {
				var hash = Argon2Hash( "password", "argon2id", 2, 1024, 3 );

				expect( hash ).toMatch( "m=1024," );
				expect( hash ).toMatch( ",t=3," );
				expect( hash ).toMatch( ",p=2\$" );
			});

		});

		describe( "Argon2Hash parameter validation", function() {

			it( "rejects parallelism outside 1-10 range", function() {
				expect( function() {
					Argon2Hash( "test", "argon2id", 11, 8, 1 );
				}).toThrow();
			});

			it( "rejects memory outside 8-100000 range", function() {
				expect( function() {
					Argon2Hash( "test", "argon2id", 1, 7, 1 );
				}).toThrow();
			});

			it( "rejects iterations outside 1-20 range", function() {
				expect( function() {
					Argon2Hash( "test", "argon2id", 1, 8, 0 );
				}).toThrow();
			});

			it( "rejects unknown variant", function() {
				expect( function() {
					Argon2Hash( "test", "argon2z" );
				}).toThrow();
			});

		});

		describe( "Argon2Hash cross-verification", function() {

			it( "hashes generated by Argon2Hash verify with Argon2Verify", function() {
				// Use low params for speed
				var hash = Argon2Hash( "password", "argon2id", 1, 8, 1 );
				expect( Argon2Verify( "password", hash ) ).toBeTrue();
			});

			it( "hashes generated by Argon2Hash verify with deprecated Argon2CheckHash", function() {
				var hash = Argon2Hash( "password", "argon2id", 1, 8, 1 );
				expect( Argon2CheckHash( "password", hash ) ).toBeTrue();
			});

			it( "hashes generated by deprecated GenerateArgon2Hash verify with Argon2Verify", function() {
				var hash = GenerateArgon2Hash( "password" );
				expect( Argon2Verify( "password", hash ) ).toBeTrue();
			});

		});

	}

}
