/**
 * Tests for BCryptHash() — the preferred BCrypt hashing function.
 *
 * History:
 *   - GenerateBCryptHash() was the original name, now deprecated.
 *   - BCryptHash() replaces it with identical defaults (cost=10).
 *   - Existing tests for the deprecated name remain in tests/BCrypt.cfc.
 */
component extends="org.lucee.cfml.test.LuceeTestCase" labels="crypto" {

	function run( testResults, testBox ) {

		describe( "BCryptHash", function() {

			it( "generates a valid BCrypt hash", function() {
				var hash = BCryptHash( "password" );

				expect( hash ).toBeString();
				expect( hash ).toMatch( "^\$2[aby]?\$\d{2}\$.{53}$" );
			});

			it( "generates different hashes for same input (random salt)", function() {
				var hash1 = BCryptHash( "password" );
				var hash2 = BCryptHash( "password" );

				expect( hash1 ).notToBe( hash2 );
			});

			it( "respects cost parameter", function() {
				var hash = BCryptHash( "password", 4 );

				expect( hash ).toInclude( "$04$" );
			});

		});

		describe( "BCryptHash cross-verification", function() {

			it( "hashes generated by BCryptHash verify with BCryptVerify", function() {
				var hash = BCryptHash( "password" );
				expect( BCryptVerify( "password", hash ) ).toBeTrue();
			});

			it( "hashes generated by BCryptHash verify with deprecated VerifyBCryptHash", function() {
				var hash = BCryptHash( "password" );
				expect( VerifyBCryptHash( "password", hash ) ).toBeTrue();
			});

			it( "hashes generated by deprecated GenerateBCryptHash verify with BCryptVerify", function() {
				var hash = GenerateBCryptHash( "password" );
				expect( BCryptVerify( "password", hash ) ).toBeTrue();
			});

		});

	}

}
