/**
 * Tests for SCryptHash() — the preferred SCrypt hashing function.
 *
 * History:
 *   - GenerateSCryptHash() was the original name, now deprecated.
 *   - SCryptHash() replaces it with identical defaults (N=16384, r=8, p=1).
 *   - Existing tests for the deprecated name remain in tests/SCrypt.cfc.
 */
component extends="org.lucee.cfml.test.LuceeTestCase" labels="crypto" {

	function run( testResults, testBox ) {

		describe( "SCryptHash", function() {

			it( "generates a valid SCrypt hash", function() {
				var hash = SCryptHash( "password" );

				expect( hash ).toBeString();
				expect( hash ).toMatch( "^\$scrypt\$ln=\d+,r=\d+,p=\d+\$.+\$.+$" );
			});

			it( "generates different hashes for same input (random salt)", function() {
				var hash1 = SCryptHash( "password" );
				var hash2 = SCryptHash( "password" );

				expect( hash1 ).notToBe( hash2 );
			});

			it( "respects cost parameters", function() {
				// Use lower cost for faster test (N=4096 = ln=12)
				var hash = SCryptHash( "password", 4096, 4, 1 );

				expect( hash ).toInclude( "ln=12" );
				expect( hash ).toInclude( "r=4" );
				expect( hash ).toInclude( "p=1" );
			});

			it( "validates cost parameter must be power of 2", function() {
				expect( function() {
					SCryptHash( "password", 1000 );
				}).toThrow();
			});

		});

		describe( "SCryptHash cross-verification", function() {

			it( "hashes generated by SCryptHash verify with SCryptVerify", function() {
				var hash = SCryptHash( "password", 4096, 4, 1 );
				expect( SCryptVerify( "password", hash ) ).toBeTrue();
			});

			it( "hashes generated by SCryptHash verify with deprecated VerifySCryptHash", function() {
				var hash = SCryptHash( "password", 4096, 4, 1 );
				expect( VerifySCryptHash( "password", hash ) ).toBeTrue();
			});

			it( "hashes generated by deprecated GenerateSCryptHash verify with SCryptVerify", function() {
				var hash = GenerateSCryptHash( "password", 4096, 4, 1 );
				expect( SCryptVerify( "password", hash ) ).toBeTrue();
			});

		});

	}

}
